version: '3.8'
services:
    nginx:
        container_name: nginx_web
        build:
            context: .
            dockerfile: ./docker/nginx.Dockerfile
        ports:
            - "8080:80"
            - "8081:443"
        volumes:
            - ./src:/usr/share/nginx/html
            - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./log/error.log:/var/log/nginx/error.log
            - ./log/access.log://var/log/nginx/access.log
        restart: always
        networks:
            - internal
    php-fpm:
        container_name: php_web
        build: 
            context: .
            dockerfile: ./docker/php.Dockerfile
        volumes:
            - ./src:/usr/share/nginx/html
        networks:
            - internal
    db:
        container_name: mysql_web
        image: mysql:latest
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root@root
            MYSQL_USER: ngn
            MYSQL_PASSWORD: ngn@ngn
            MYSQL_DATABASE: web
        volumes:
            - ./db:/var/lib/mysql/
        networks:
            - internal

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: PMA_web

        networks:
            - internal
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8082:80
networks:
    internal:
        driver: bridge